### ISSUE TITLE
updateArticle adds new article to the list

### ISSUE THREAD

**Issue by athif23** [Leoat12/toread-cli#4]
### Here's what I try to do:
1. Run the `to-read saveArticle https://someurl.com`
2. Check the list to see the id. `to-read list`
3. Run `to-read updateArticle 1 --tags website --addTags true`
4. Here's the error happens, instead of just updating the article it creates a new article which has the same id, name, and tags.

It looks like this:
		
		1# Website
		[website]

		1# Website
		[website]

We have to find out why this happens. @Leoat12 Can you please check that out? 
I also will try to look at the code and try to figure out why it happens.

#### Let's solve this.

**Comment by Leoat12** [comment]
The problem is in this line: `file.articles = file.articles.filter(a => a.id !== id);`
The double equal there makes it a deep inequality, it is the contrary of "===". I confess that I still don't know why, I will have to study that, but inputs coming from Commander, despite coming as `number` doesn't pass this equality.  That's why in this line in the same method, `updateArticle`, I use a simple equality: 
```typescript
let existentArticle: Article | undefined = file.articles.find(
            a => a.id == id
 );
```  
It is the same when I want to filter the list to have the items but the one I'm updating, therefore:
`file.articles = file.articles.filter(a => a.id != id);`

I will commit the fix, which will also fix the test, which didn't assert whether the item was duplicated during the update, like it was happening.
