### ISSUE TITLE
App's performance is a bit too slow

### ISSUE THREAD

**Issue by athif23** [Leoat12/toread-cli#5]
I don't know on other computers, but on my computer, the app's processing feels a bit too slow. I need to wait for maybe a minutes or so, just to see the list of articles. And, that's slow... if we compare to other apps.

But well, we need to make this app be faster, maybe like, make a bundled using webpack or rollup, removing unnecessary code or something else.

And, I propose that we should use webpack or rollup or parcel, to make the app smaller by bundled it up.

#### Thanks.

**Comment by athif23** [comment]
Ok, I feel like this is not really matter anymore, because I think it's really up to the computer itself. If the computer is fast then it will run fast if not then it's not.

So, I will close this issue, but I will keep trying to make the app faster with parcel(maybe) or removing some unnecessary thing.

**Comment by Leoat12** [comment]
I approve the idea of always trying to improve performance. I never used Parcel, but I will study about that and other bundlers, it is an interesting idea. 
The thing is that I'm very used to slow application in nodejs, I never found one that I was satisfied with the performance, that's why I don't feel like it has been any difference from others when it comes to that.
